@startuml customer
class Cart
abstract class User
class Customer {
    - Cart cart
    + Customer(String name)
    + boolean addToCart(Item item, int quantity)
    + boolean removeFromCart(Item item, int quantity)
    + double getTotal()
    + Cart getCart()
    + String getCartItemList()
    + String toString()
}
User <|-- Customer
Customer *- Cart
@enduml