@startuml manager
class Store
abstract class User
class Manager {
    - Store store
    + Manager(String name)
    + boolean openStore(String storeName)
    + boolean closeStore()
}
User <|-- Manager
Manager *- Store
@enduml