@startuml Cart
class Item
class Cart {
    - Map<Item, Integer> itemToQuantityMap
    + Cart()
    + Cart(List<CartItem> purchases)
    + double getTotalCost()
    + List<CartItem> getPurchases()
    + void setQuantityForItem(Item item, int quantity)
    + int getQuantityForItem(Item item)
    + int removeItem(Item item)
    + void clearCart()
    + String displayCartItems()
    + String toString()
}
Cart o- Item
@enduml