@startuml catalog
class Item
class Catalog {
    - List<Item> catalogItems
    + Catalog()
    + boolean addToCatalog(Item item)
    + boolean removeFromCatalog(Item item)
    + List<Item> getAvailableItems()
    + Item getItem(Item item)
    + Item getItem(String searchParameter)
    + void update(Observable observable, Object arg)
    + String toString()
}
Catalog o- "0..*" Item
@enduml