@startuml inventory
class Item
class Inventory {
    private HashMap<Item, Integer> inventoryMap
    private HashMap<String, Item> upcMap
    public Inventory()
    public boolean addItem(Item item, int increment)
    public boolean addItem(Item item)
    public boolean removeItem(Item item, int decrement)
    public boolean removeItem(Item item)
    public boolean removeItem(String item, int decrement)
    public boolean removeItem(String item)
    public boolean deleteItem(Item item)
    public boolean deleteItem(String upc)
    public Item getItem(String upc)
    public Item getItem(Item item)
    public void printInventory()
    public HashMap getInventory()
    public String toString()
}
Inventory o- "0..*" Item
@enduml