@startuml store
class Catalog
class Inventory
class Store {
    - String storeName
    - Inventory inventory
    - Catalog catalog
    - boolean isOpen
    + void initializeStore()
    - Store()
    + Store(String storeName)
    + boolean open()
    + boolean close()
    + boolean addToInventory(Item item, int quantity)
    + boolean addToInventory(Item item)
    + boolean removeFromInventory(Item item)
    + boolean removeFromInventory(Item item, int quantity)
    + boolean removeFromInventory(String upc)
    + boolean removeFromInventory(String upc, int quantity)
    + void printInventory()
    + boolean addToCatalog(Item item)
    + boolean removeFromCatalog(Item item)
    + List<Item> getAvailableItems()
    + Item searchItem(Item item)
    + Item searchItem(String searchParameter)
    + void printCatalog()
    + boolean isOpen()
    + String toString()
}
Store *- Inventory
Store *- Catalog
@enduml