@startuml package
skinparam defaultFontSize 18
left to right direction

JPanel <|-- MiddlePanel
Dimension --* MiddlePanel

class MiddlePanel {
    - {static} final int MAX_WIDTH
    - {static} final int MAX_HEIGHT
    - Dimension dimension

    + MiddlePanel(AddItemPanel.Delegate addItemDelegate, CartItemPanel.Delegate cartItemDelegate, Catalog catalog, Cart cart)
}

@enduml