@startuml post
class Store
class POST {
  + final int postid
  - static int idCount
  - Store store
  + POST()
  + Transaction checkout(Customer customer, String paymentType, String cardNumber)
  + boolean addItemToCatalog(Item item)
  + boolean removeItemFromCatalog(Item item)
  + boolean addItemToInventory(Item item)
  + boolean removeItemFromInventory(Item item)
  + boolean openStore()
  + boolean closeStore()
  + Store getStore()
}


POST *- Store
@enduml